### ISSUE TITLE
Eclipse IDE Failed To Resolve for Binding with "org.eclipse.smarthome.io.transport.mqtt" import - Dependency on Dagger lib

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab-core#1238]
Hi,

While migrating my own 2.4 binding to 2.5 and new build system, i am hitting problem related to MQTT when i try to use "org.eclipse.smarthome.io.transport.mqtt". CHeers

> 
> Resolution failed. Capabilities satisfying the following requirements could not be found:
>     [<<INITIAL>>]
>       ⇒ osgi.identity: (osgi.identity=org.openhab.binding.ziggonext)
>           ⇒ [org.openhab.binding.ziggonext version=2.5.0.201911162153]
>               ⇒ osgi.wiring.package: (&(osgi.wiring.package=org.eclipse.smarthome.io.transport.mqtt))
>                   ⇒ [org.openhab.core.io.transport.mqtt version=2.5.0.201911150310]
>                       ⇒ osgi.wiring.package: (&(osgi.wiring.package=com.hivemq.client.mqtt.datatypes)(&(version>=1.1.0)(!(version>=2.0.0))))
>                           ⇒ [com.hivemq.client.mqtt version=1.1.2]
>                               ⇒ osgi.wiring.package: (&(osgi.wiring.package=dagger))

**Comment by cweitkamp** [comment]
Has this issue been addressed by https://github.com/openhab/openhab-core/pull/1246?

**Comment by mherwege** [comment]
Unless I am still missing something, it does not for me, see [forum](https://community.openhab.org/t/struggling-with-mqtt-in-development-of-new-binding/85631/15?u=mherwege).
