### ISSUE TITLE
[ThingTypeXmlProvider] Could not register ThingType

### ISSUE THREAD

**Issue by andrewfg** [openhab/openhab-core#1445]
Hi, I noticed this Error in my log file. I don't know if this is an issue with the OH core, or with the ZWave binding...
```
2020-04-23 15:36:49.071 [ERROR] [ng.xml.internal.ThingTypeXmlProvider] - Could not register ThingType: zwave:aeotec_zw141_03_000
java.lang.IllegalArgumentException: ID segment ' switch_dimmer' contains invalid characters. Each segment of the ID must match the pattern [A-Za-z0-9_-]*.
	at org.eclipse.smarthome.core.common.AbstractUID.validateSegment(AbstractUID.java:97) ~[bundleFile:?]
	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:75) ~[bundleFile:?]
	at org.eclipse.smarthome.core.common.AbstractUID.<init>(AbstractUID.java:49) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.UID.<init>(UID.java:48) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.type.ChannelTypeUID.<init>(ChannelTypeUID.java:40) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ChannelXmlResult.toChannelDefinition(ChannelXmlResult.java:135) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toChannelDefinitions(ThingTypeXmlResult.java:98) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.getBuilder(ThingTypeXmlResult.java:148) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlResult.toThingType(ThingTypeXmlResult.java:156) ~[bundleFile:?]
	at org.eclipse.smarthome.core.thing.xml.internal.ThingTypeXmlProvider.addingFinished(ThingTypeXmlProvider.java:148) [bundleFile:?]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.addingFinished(XmlDocumentBundleTracker.java:265) [bundleFile:?]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.parseDocuments(XmlDocumentBundleTracker.java:424) [bundleFile:?]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.processBundle(XmlDocumentBundleTracker.java:398) [bundleFile:?]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker.access$6(XmlDocumentBundleTracker.java:393) [bundleFile:?]
	at org.eclipse.smarthome.config.xml.osgi.XmlDocumentBundleTracker$2.run(XmlDocumentBundleTracker.java:363) [bundleFile:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_222]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_222]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_222]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_222]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]

```

**Comment by mhilbush** [comment]
This was an issue with one of the wave database entries. It was discussed heavily on the forum. It is resolved in recent snapshots of the zwave binding.

**Comment by cdjackson** [comment]
Please update to the latest snapshot as this was resolved already.

**Comment by andrewfg** [comment]
> Please update to the latest snapshot as this was resolved already.

@cdjackson I am running OpenHabian in Raspberry Pi; I just used the OpenHabian configuration console to pull the latest snapshot; the latest snapshot that it pulls is 2.5.4-1; and the bug is NOT fixed in that version; this may be a problem that the OpenHabian configuration console is not really pulling the REALLY latest snapshot; or??

**Comment by cdjackson** [comment]
You need to download the snapshot versions - not the releases. Snapshots are 2.5.5 - you are on 2.5.4 which will never change as it’s a fixed version.

**Comment by andrewfg** [comment]
@cdjackson my point is that the openhabian configuration console is SUPPOSED to pull the latest snapshot, but in fact it is pulling v2.5.4-1 which is NOT the latest snapshot. So there is an issue with openhabian configuration console!

**Comment by cdjackson** [comment]
I suggest you report that in the appropriate place.

**Comment by andrewfg** [comment]
> I suggest you report that in the appropriate place.

Done here https://community.openhab.org/t/openhabian-config-tool-not-pulling-latest-snapshot/97726 -- it seems that the 2.5.5-snapshot has not yet been deployed to the user download repository => so the advice posted earlier in this thread "upgrade to latest snapshot" -- cannot be followed...

**Comment by cdjackson** [comment]
Why not try installing it manually then. Download the snapshot and install it into the addons folder?

**Comment by andrewfg** [comment]
No thanks. That's too messy for me.

**Comment by cdjackson** [comment]
Ok, then I guess it’s not that the instructions _can’t_ be followed, but you don’t want to ;)

You’ll just have to wait then until your distribution is updated - sorry.

**Comment by andrewfg** [comment]
All OK now; the v2.5.5-SNAPSHOT has finally been pushed to the general user's distro
