### ISSUE TITLE
Disconnecting USB device causes Java to exit with 2.5

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab-core#1492]
I'm trying improve how the Insteon binding handles reconnects.  During my testing of the PLM which uses a USB port, Java exits with no error in the following situation on Linux 

1. disconnect a working USB device, this causes a IOException to get thrown
1. close the IO streams associated with the device
1. open the USB device

This causes Java to exit in gnu.io.CommPortIdentifier.open():

```
throw new gnu.io.PortInUseException(
	native_psmisc_report_owner(PortName));
```
With nrjavaserial-3.14.0.jar, this is line 474 in CommPortIdentifier.java.

It appears that Java is crashing while trying to call the native method `native_psmisc_report_owner`.

This appears to be the same as https://code.google.com/archive/p/nrjavaserial/issues/27

**Comment by wborn** [comment]
I've created https://github.com/NeuronRobotics/nrjavaserial/issues/180 for this recently.

**Comment by robnielsen** [comment]
@wborn, this might be different. Here's the code:

```
SerialPortIdentifier spi = serialPortManager.getIdentifier(devName);
if (spi == null) {
    logger.warn("{} is not a valid serial port.", devName);
    return false;
}

port = spi.open(appName, 1000);
```

I created https://github.com/NeuronRobotics/nrjavaserial/issues/181 for this issue.

**Comment by wborn** [comment]
Did you also test using nrjavaserial 5.1+?
It has [several fixes](https://github.com/NeuronRobotics/nrjavaserial/releases/tag/5.1.0) when USB devices are unplugged.

**Comment by wborn** [comment]
I've created a reversioned nrjavaserial 5.1.1 bundle that can also be easily used with OH 2.5.x.
See: https://github.com/openhab/org.openhab.binding.zwave/issues/1332#issuecomment-629069306.

**Comment by robnielsen** [comment]
@wborn, I gave 5.1.1 a try and it still crashes. I renamed the old library by appending .old:
```
$ ls -l runtime/system/org/openhab/nrjavaserial/3.15.0.OH2/*
-rw-r--r-- 1 rob rob 728329 May 22 08:17 runtime/system/org/openhab/nrjavaserial/3.15.0.OH2/nrjavaserial-3.15.0.OH2.jar
-rw-r--r-- 1 rob rob 748907 May 20 05:28 runtime/system/org/openhab/nrjavaserial/3.15.0.OH2/nrjavaserial-3.15.0.OH2.jar.old
$ unzip -l runtime/system/org/openhab/nrjavaserial/3.15.0.OH2/nrjavaserial-3.15.0.OH2.jar
Archive:  runtime/system/org/openhab/nrjavaserial/3.15.0.OH2/nrjavaserial-3.15.0.OH2.jar
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  2020-05-09 13:09   META-INF/
     1237  2020-05-15 01:31   META-INF/MANIFEST.MF
        0  2020-05-09 13:09   com/

```

**Comment by robnielsen** [comment]
This should be fixed in nrjavaserial 5.2.0.

**Comment by wborn** [comment]
It doesn't seem to fix the other issue https://github.com/NeuronRobotics/nrjavaserial/issues/180.
At least the whole JVM doesn't exit now which is certainly an improvement. :wink:

**Comment by robnielsen** [comment]
@wborn, let me know if you have a reversioned bundle like you have above for 5.1.1. If so, I'll give it a try.

**Comment by wborn** [comment]
I've reversioned 5.2.1 in this [nrjavaserial-3.15.0.OH2.jar](https://github.com/wborn/nrjavaserial/releases/download/reversioned521/nrjavaserial-3.15.0.OH2.jar).

**Comment by robnielsen** [comment]
This is fixed with 5.2.1

**Comment by wborn** [comment]
That's certainly nice! There's still https://github.com/NeuronRobotics/nrjavaserial/issues/111 that may cause the library fail to reconnect after the device has been unplugged for a while and you then reconnect it. :slightly_frowning_face:

**Comment by robnielsen** [comment]
@wborn,
Java is no longer crashing, but the library still isn't working correctly either. On disconnect, the following code:

```
SerialPortIdentifier spi = serialPortManager.getIdentifier(devName);
if (spi == null) {
    logger.warn("{} is not a valid serial port.", devName);
    return false;
}
```

spi is false. It should be true.

**Comment by robnielsen** [comment]
I tried calling `serialPortManager.getIdentifier(devName)` once, and started to get the `PortInUseException`. But this created a new issue, the `PortInUseException `continued to get thrown after the device is plugged back in.

**Comment by wborn** [comment]
Let's close this since the original issue is fixed with nrjavaserial 5.2.1.

If you have more nrjavaserial related issues, please create issues for these in the [nrjavaserial issue tracker](https://github.com/NeuronRobotics/nrjavaserial/issues). That way they will be fixed sooner because the nrjavaserial maintainers don't look for issues in their library in this tracker. :wink:
