### ISSUE TITLE
Channel copy don't respect field changes

### ISSUE THREAD

**Issue by mti-sk** [openhab/openhab-core#4458]
Hi,
When I try to make a copy of a channel on any thing in my version of openhab, the copy is created, but except for the channel name, all the edited fields are unchanged. Which is not even obvious at first glance (you are under the impression that you have a new channel with different settings). The copy is completely identical to the template, without any modifications made.

## Expected Behavior
When I fill in or overwrite a field in the copy of the channel, my change is reflected in the newly created channel. 

## Current Behavior
Unfortunately, it is not like that. The edited field is not reflected in the copy. This is the source of unexpected behavior.

## Possible Solution
Apparently, this is an error when creating the copy. No changes have been made to individual fields in the copy.
The solution is twofold:
1. reflect the required field modifications in the created copy
2. make it clear to the user that when the copy is created, any field modifications will not be taken into account, for example by disabling the fields.

## Steps to Reproduce (for Bugs)
1. Create any thing
2. Create a channel "channel1" and fill in the values ​​like MQTT State Topic or MQTT Command Topic,...
3. Mark the channel created in point 2 and make a copy of it
4. In the copy "channel1_copy" change the fields like MQTT State Topic or MQTT Command Topic,...
5. Save the copy
6. When you open the copy "channel1_copy" the fields will remain the same as the channel "channel1", even if you have modified the fields.

## Your Environment
OpenHAB 4.2.2 
Odroid N2+ (ARM)

**Comment by florian-h05** [comment]
Could you please elaborate a bit more where this issue happens?
When copying channels in the UI or in a .things file?

**Comment by florian-h05** [comment]
Nevermind, this is not needed, I just created a fix for this bug.
For future bugs like this, please create them in openhab-webui, as most Things going wrong in the UI are actual UI bugs and not core bugs.

**Comment by florian-h05** [comment]
@openhab/core-maintainers Can you please close this issue as it has been fixed in https://github.com/openhab/openhab-webui/pull/2891?

**Comment by matmai** [comment]
I still have issues with the value transformation of a channel copy, please have a look at #2770.
