### ISSUE TITLE
[Automation] disable and enable rules

### ISSUE THREAD

**Issue by itskeKs** [openhab/openhab-core#722]
when i create a rule which disables another rule then the disabled rule first switches to uninitialized and then to disabled. after it gets enabled back again it is stated as active but does not execute any command within that rule. i have to save the rule manually and after that it starts working again.

that bug appeared with 2.4.0 and is still present within 2.5.0.

does anyone have a workaround for that? i am back on 2.3.0 because i was not able to get the rule engine to work properly.

**Comment by openhab-5iver** [comment]
@itskeKs, please change [Bug] to [Automation] in the title.

Possibly related to #636.

**Comment by openhab-5iver** [comment]
@itskeKs, please test again with build S1583 or newer. Your issue may have been resolved by #776.

**Comment by maggu2810** [comment]
No need to test. See #783

**Comment by itskeKs** [comment]
@openhab-5iver @maggu2810 i upgrade ro Version: 2.5.0~S1584-1 issue is still there :(

`2019-05-05 12:32:54.391 [.event.RuleStatusInfoEvent] - 42c1743b-8aa7-4b7f-b9e4-9715d4eaca0b updated: RUNNING
2019-05-05 12:32:54.402 [.event.RuleStatusInfoEvent] - 85fabed7-7ede-432e-a3ac-7042676fef34 updated: UNINITIALIZED (DISABLED)
2019-05-05 12:32:54.411 [.event.RuleStatusInfoEvent] - 42c1743b-8aa7-4b7f-b9e4-9715d4eaca0b updated: IDLE
2019-05-05 12:33:05.923 [.event.RuleStatusInfoEvent] - 3ca83d09-480c-4eda-a081-fb37d9285b1c updated: RUNNING
2019-05-05 12:33:05.933 [.event.RuleStatusInfoEvent] - 85fabed7-7ede-432e-a3ac-7042676fef34 updated: IDLE
`

**Comment by maggu2810** [comment]
@itskeKs I was not aware about any change in the code base that has been contributed that solves this bug. So, it will be there as long as no one fixed it.

**Comment by maggu2810** [comment]
You could check the latest sources if the problem is solved now.

**Comment by itskeKs** [comment]
@maggus2810 how long does it normally take for the code to be within a nightly/testing openhab2 build? i think i won‘t be able to build from source :|

**Comment by maggu2810** [comment]
I assume this question needs to be answered by the maintainer of the openHAB distribution of the openHAB infrastructure or perhaps somebody else who nows the openHAB build cycles -- I'm not one of those guys.

**Comment by kaikreuzer** [comment]
Simple. Just check when the latest build of openhab-core was done (https://ci.openhab.org/job/openHAB-Core/) -> yesterday
and that a distro build (https://ci.openhab.org/job/openHAB-Distribution/) happened after that -> yes

**Comment by openhab-5iver** [comment]
@itskeKs, just checking in to see if you have had a chance to test this. I've tested on S1603 and it appears to be working properly now.

**Comment by itskeKs** [comment]
@openhab-5iver sorry for my late reply. i has no chance to test since the yeelight 2.5.0 plugin does not work properly. it does not discover any bulb. using older version of the plugin does discover the bulbs but i can not control them. so i was not able to create rules which would turn on/off my lights. i will check if there was an update for the yeelight plugin in the last weeks maybe it was fixed already.

**Comment by cweitkamp** [comment]
@itskeKs Any news on this? I will close it for now. Please reopen it if your issue is still present.
